version: 0.1  
phases:        
     pre_build:
        commands:
            - npm install
     build:
        commands:                    
     post_build:
        commands:
            - node app.js
artifacts:
    files:
       /*       
